### ISSUE TITLE
errors in test log

### ISSUE THREAD

**Issue by agardou** [Opla/backend#38]
when running test suite, all tests pass but we get an error log  (at tests end) : 

$ yarn test
yarn run v1.5.1
$ jest
 PASS  tests\controllers\metrics.test.js

 PASS  tests\controllers\index.test.js
 PASS  tests\controllers\bots.test.js

 PASS  tests\middlewares\openNLX.test.js

 RUNS  tests/api.test.js
 RUNS  tests/controllers/bots.test.js
 RUNS  tests/api.test.js
 PASS  tests\models\bots.test.js.js
 PASS  tests\routes\metrics.test.js

 RUNS  tests/api.test.js
 RUNS  tests/routes/metrics.test.js
 RUNS  tests/models/bots.test.js

Test Suites: 4 passed, 4 of 7 total
Tests:       5 passed, 5 total
Snapshots:   0 total
Time:        5s2018-03-27T12:26:48.909Z - info: OpenNLX onDispatch:  messenger newMessages
2018-03-27T12:26:48.915Z - info: OpenNLX onDispatch:  bot updateBot
2018-03-27T12:26:48.920Z - info: OpenNLX onDispatch:  bot updateBot
2018-03-27T12:26:48.925Z - info: OpenNLX onDispatch:  bot updateBot
2018-03-27T12:26:48.933Z - info: putIntents not same version:  null
2018-03-27T12:26:48.934Z - info: OpenNLX onDispatch:  bot setIntents
2018-03-27T12:26:48.937Z - info: putIntents not same version:  null
2018-03-27T12:26:48.938Z - info: OpenNLX onDispatch:  bot setIntents
2018-03-27T12:26:48.941Z - info: putIntents not same version:  null
2018-03-27T12:26:48.942Z - info: OpenNLX onDispatch:  bot setIntents
2018-03-27T12:26:48.945Z - info: putIntents not same version:  null
 RUNS  tests/api.test.js

Test Suites: 6 passed, 6 of 7 total
Tests:       8 passed, 8 total
Snapshots:   0 total
Time:        5s2018-03-27T12:26:48.974Z - info: Stop Zoapp backend
2018-03-27T12:26:48.976Z - info: Start Opla.ai test 0.8.0
2018-03-27T12:26:48.978Z - info: will init
2018-03-27T12:26:48.978Z - info: initMiddlewares
2018-03-27T12:26:48.992Z - error: error while connecting to MySQLDatabase: ER_BAD_DB_ERROR
 RUNS  tests/api.test.js

Test Suites: 6 passed, 6 of 7 total
Tests:       8 passed, 8 total
Snapshots:   0 total
Time:        6s2018-03-27T12:26:49.760Z - info: Unknown character at line 15 91
 RUNS  tests/api.test.js

 PASS  tests\api.test.js of 7 total
  ● Console

    console.error node_modules\jest-jasmine2\build\jasmine\Env.js:160
      Unhandled error
    console.error node_modules\jest-jasmine2\build\jasmine\Env.js:161
      TypeError: Cannot read property '0' of null
          at MySQLTable.getItem (C:\Users\Adrien\workspace\opla-backend\node_modules\src\database\mysql\mysqlTable.js:463:17)
          at <anonymous>
          at process._tickCallback (internal/process/next_tick.js:188:7)

Test Suites: 7 passed, 7 total
Tests:       52 passed, 52 total
Snapshots:   0 total
Time:        7.429s
Ran all test suites.
Done in 8.40s.

**Comment by willdurand** [comment]
should be fixed now
